services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - ENV=production
      - DB_DRIVER=sqlite
      - DB_DSN=file:/root/data/cms.db?_pragma=journal_mode(WAL)&_pragma=busy_timeout=5000
    volumes:
      - ./content:/root/content
      - ./static/images:/root/static/images
      - ./static/videos:/root/static/videos
      - ./data:/root/data
    restart: unless-stopped
    networks:
      - soma-network

networks:
  soma-network:
    driver: bridge