services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - ENV=production
    volumes:
      - ./content:/root/content
      - ./static/images:/root/static/images
      - ./static/videos:/root/static/videos
    restart: unless-stopped
    networks:
      - soma-network

networks:
  soma-network:
    driver: bridge